### ISSUE TITLE
Attempts to locate scraper under --output directory

### ISSUE THREAD

**Issue by bcarradini** [ContentMine/quickscrape#102]
After installing quickscrape and journal-scrapers and executing the example provided at https://github.com/ContentMine/quickscrape#examples, quickscrape fails because it attempts to locate the specified scraper within the specified output directory:

Barbaras-MacBook-Pro:data-mining-abs barbara$ quickscrape --url https://peerj.com/articles/384 --scraper journal-scrapers/scrapers/peerj.json --output peerj-384 --outformat bibjson
info: quickscrape 0.4.7 launched with...
info: - URL: https://peerj.com/articles/384
info: - Scraper: /Users/barbara/Dev/data-mining-abs/peerj-384/journal-scrapers/scrapers/peerj.json
info: - Rate limit: 3 per minute
info: - Log level: info
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/barbara/Dev/data-mining-abs/peerj-384/journal-scrapers/scrapers/peerj.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.<anonymous> (/Users/barbara/.nvm/versions/node/v8.9.1/lib/node_modules/quickscrape/bin/quickscrape.js:138:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)

**Comment by bcarradini** [comment]
I was able to work around this problem by making the following adjustment to quickscrape.js:
if (program.scraper) {
  // program.scraper = path.resolve(program.scraper);
  program.scraper = '/Users/barbara/Dev/data-mining-abs/'+program.scraper;
  log.info('- Scraper:', program.scraper);
}

**Comment by code56** [comment]
> I was able to work around this problem by making the following adjustment to quickscrape.js:
> if (program.scraper) {
> // program.scraper = path.resolve(program.scraper);
> program.scraper = '/Users/barbara/Dev/data-mining-abs/'+program.scraper;
> log.info('- Scraper:', program.scraper);
> }

Hello, thanks for posting your solution. I am having the same issue. Where about in the quick scrape.js should I put this piece of code please? thanks again.

**Comment by code56** [comment]
> I was able to work around this problem by making the following adjustment to quickscrape.js:
> if (program.scraper) {
> // program.scraper = path.resolve(program.scraper);
> program.scraper = '/Users/barbara/Dev/data-mining-abs/'+program.scraper;
> log.info('- Scraper:', program.scraper);
> }

thank you for sharing your solution.

**Comment by bcarradini** [comment]
This is the original code block in quickscrape.js:
```if (program.scraper) {
  program.scraper = path.resolve(program.scraper);
  log.info('- Scraper:', program.scraper);
}
```

**Comment by bcarradini** [comment]
> > I was able to work around this problem by making the following adjustment to quickscrape.js:
> > if (program.scraper) {
> > // program.scraper = path.resolve(program.scraper);
> > program.scraper = '/Users/barbara/Dev/data-mining-abs/'+program.scraper;
> > log.info('- Scraper:', program.scraper);
> > }
> 
> thank you for sharing your solution.

@code56

**Comment by bcarradini** [comment]
Well... I didn't mean to close this issue, but apparently there's no way to re-open an accidentally closed issue. Anyway:

@code56, here's an answer to your question.

This code block is in quickscrape.js already:
```
if (program.scraper) {
  program.scraper = path.resolve(program.scraper);
  log.info('- Scraper:', program.scraper);
}
```

Replace the second line with the following, as appropriate for your environment:
```
program.scraper = '/PATH/TO/SCRAPER/'+program.scraper;
```

**Comment by blahah** [comment]
reopened as it was accidentally closed - thanks @bcarradini for the temp fix

we need a solution in the code base before we close this
